server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc.throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true