spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

  # mysql数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://192.168.1.100:1433;DatabaseName=chaipxingtai
    username: sa
    password: sasa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialSize: 5
    minIdle: 5
    maxActive: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# Logging configuration
logging:
  level:
    com.bzh.floodserver.mapper: debug
      #Spring Security 相关设置
      #org.springframework:
    #security: DEBUG
  #file: /springboot.log
  #path: /var/log/tomcat/
debug: false

# token 请求头的名字
token.header: X_Auth_Token
# token 加密密钥
token.secret: secret
# token 过期时间，以秒为单位，604800 是 一星期
token.expiration: 604800

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
  #type-aliases-package: com.bzh.floodserver.model
